### ISSUE TITLE
IT8587

### ISSUE THREAD

**Issue by junocomp** [OscarL/it87#1]
Any chance of supporting IT8587? Most, if not all Clevo laptops have this chip.

https://github.com/lm-sensors/lm-sensors/issues/380

**Comment by OscarL** [comment]
I doubt I'll ever work on that, sorry! Reasons:

- Way too many things on my ToDo list.
- I don't have the necessary hardware to test.
- That IT8587 (after a cursory glance to its documentation) doesn't looks like a direct match for the chips *this* driver for **Haiku** aims to support.

Sorry again, but... I better not leave you waiting in vain.
